name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy tindog to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './tindog'
          production-branch: main
          github-token: ${{ secrets.TOKEN_GITHUB }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.TINDOG_ID }}
        timeout-minutes: 1
